site_name: Sentiment Analysis API
site_description: "A FastAPI microservice for text sentiment analysis with pytest, ruff, and Docker support"
site_url: https://v-asura.github.io/sentiment-analysis-api

repo_url: https://github.com/v-asura/sentiment-analysis-api
edit_uri: blob/master/docs/

copyright: © 2025 v-asura

theme:
  name: material
  # custom_dir: docs/overrides  # Uncomment if using overrides
  color_mode: auto
  user_color_mode_toggle: true
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.tracking
    - navigation.top
    - search.share
    - search.suggest

markdown_extensions:
  - tables
  - attr_list
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences # Enables tabbed content
  - pymdownx.tabbed: # Explicitly enable tabbed extension
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - git-revision-date-localized

nav:
  - Home: index.md
  - Setup: setup.md
  - Configuration: configuration.md
  - Development Notes: development.md
