name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting and formatting
        run: |
          pip install ruff
          ruff check sentiment_analysis_api/
          ruff format sentiment_analysis_api/ --check

      - name: Run tests
        run: |
          pip install pytest pytest-asyncio pytest-cov
          python -m pytest sentiment_analysis_api/tests/ --cov=sentiment_analysis_api --cov-report=xml

      - name: Build Docker image
        run: |
          docker build -t sentiment-api:latest .
